services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - .:/IIDE/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: blogDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - intenalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    volumes:
      - .:/IIDE/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'pass'
      DB_DATABASE: blogDB
      DB_CONNECTION_LIMIT: 20
      PORT: 3000
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
    depends_on:
      - mysqldb
    networks:
      - intenalnet

networks:
  intenalnet:
    driver: bridge
