CREATE DATABASE IF NOT EXISTS blogDB;

USE blogDB;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS blogs;


-- create

CREATE TABLE
    users (
        Users_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
        First_name VARCHAR(255) DEFAULT NULL,
        Last_name VARCHAR(255) DEFAULT NULL,
        Email VARCHAR(255) DEFAULT NULL,
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT User_email UNIQUE (Email)
    );

CREATE TABLE
    blogs (
        Blog_id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        Title VARCHAR(400) DEFAULT NULL,
        Messages VARCHAR(10000) DEFAULT NULL,
        Images VARCHAR(2083) DEFAULT NULL,
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        Users_id BIGINT UNSIGNED NOT NULL ,
        FOREIGN KEY (Users_id) REFERENCES users(Users_id)
    );